#!/usr/bin/env bash
# BEGIN SCRIPT VERSION
# Source version: 2025-03-30 (Git 07195eb)
if [[ "${BASH_SOURCE[0]}" == "$0" && "${1-}" == --version ]]; then
    printf '%s %s (Git %s)\n' 'flameshot_wrapper' '2025-03-30' '07195eb'
    exit 0
fi
# END SCRIPT VERSION

if [ "$1" = "activewindow" ]; then
	# Get active window geometry
	eval $(xdotool getactivewindow getwindowgeometry --shell)
	REGION="${WIDTH}x${HEIGHT}+${X}+${Y}"
elif [ "$1" = "selectwindow" ]; then
	# Let the user select a window and get its geometry
	eval $(xdotool selectwindow getwindowgeometry --shell)
	REGION="${WIDTH}x${HEIGHT}+${X}+${Y}"
else
	# Get current screen
	SCREEN=$(xdotool get_desktop)
	REGION="screen${SCREEN}"
fi

# Launch the screenshot gui
flameshot gui --region "$REGION"
